name: example-action

inputs:
  input_1:
    description: 'Input 1'
    required: true

runs:
  using: "composite"
  steps:
    - name: get caller ref
      uses: lonely-takumi/reusable-workflow-repository/.github/actions/get-caller-ref@main
      with:
        action-path: ${{ github.action_path }}

    - name: step 1
      shell: bash
      run: echo ${{ inputs.input_1 }}
    
    - name: check step 1
      shell: bash
      run: |
        if [ "${{ inputs.input_1 }}" == "masterId" ]; then
          echo "step 1 success"
        else
          echo "step 1 failed"
        fi
    
    - name: step 2
      shell: bash
      run: echo "step 2"