name: example-action

inputs:
  input_1:
    description: 'Input 1'
    required: true

runs:
  using: "composite"
  steps:
    - name: step 1
      shell: bash
      run: echo ${{ inputs.input_1 }}
    
    - name: step 2
      shell: bash
      run: echo "step 2"