name: get caller ref

inputs:
  action-path:
    required: true
  # github-token:
  #   required: true

outputs:
  logFilePath:
    value: ${{ steps.get-caller-ref.outputs.logFilePath }}

runs:
  using: "composite"
  steps:
    - name: get caller ref
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        echo "job id: ${{ github.job }}"
        if [ -z "${{ inputs.action-path }}" ]; then
          jobId=$(gh api -H "Accept: application/vnd.github+json" \
                    -H "X-GitHub-Api-Version: 2022-11-28" \
                    /repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs \
                    --jq '.jobs[] | select(.name | endswith(" / ${{ github.job }}")) | .id' \
                    | head -n 1)
          nowdatetime=$(date "+%Y%m%d %H%M%S")
          echo "nowdatetime: $nowdatetime"
          logFilePath=${{ github.workspace }}/$nowdatetime_log.txt
          gh api -H "Accept: application/vnd.github+json" \
                    -H "X-GitHub-Api-Version: 2022-11-28" \
                    /repos/${{ github.repository }}/actions/jobs/$jobId/logs > $logFilePath
          cat $logFilePath
          # sed -n 's/.*-> \(.*\) (.*/\1/p' "log.txt"
          # sed -n 's/.*-> \(.*\) (.*/\1/p' "log.txt" | cut -d"@" -f2 | cut -d "/" -f 3
          sed -n 's/.*-> \(.*\) (.*/\1/p' $logFilePath
          sed -n 's/.*-> \(.*\) (.*/\1/p' $logFilePath | cut -d"@" -f2 | cut -d "/" -f 3
          echo "logFilePath=$logFilePath" | tee -a $GITHUB_OUTPUT
        else
          echo "actionPath: ${{ inputs.action-path }}"
        fi
      shell: bash