name: get caller ref

inputs:
  action-path:
    required: true
  # github-token:
  #   required: true

runs:
  using: "composite"
  steps:
    - name: get caller ref
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh api -H "Accept: application/vnd.github+json" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  /repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs
        echo "job id: ${{ job.id }}"
        gh api -H "Accept: application/vnd.github+json" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  /repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs \
                  --jq '.jobs[] | select(.name | endswith(" / ${{ github.job }}") and .status == "in_progress") | .id | first'
      shell: bash