name: get caller ref

inputs:
  action-path:
    required: true
  # github-token:
  #   required: true

runs:
  using: "composite"
  steps:
    - name: get caller ref
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh api -H "Accept: application/vnd.github+json" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  /repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs
        echo "job id: ${{ job.id }}"
        jobId=$(gh api -H "Accept: application/vnd.github+json" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  /repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs \
                  --jq '.jobs[] | select(.name | endswith(" / ${{ github.job }}")) | .id' \
                  | head -n 1)
        gh api -H "Accept: application/vnd.github+json" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  /repos/${{ github.repository }}/actions/jobs/$jobId/logs > log.txt
        sed -n 's/.*-> \(.*\) (.*/\1/p' "log.txt"
      shell: bash