name: Reusable Workflow

on:
    workflow_call:
        inputs:
            input_1:
                description: "input 1"
                required: true
                type: string
            id:
                required: false
                type: string
        secrets:
            cloud_id:
                required: true
                description: "Azure Id"

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: print input
              run: echo "${{ inputs.input_1 }}"
            - name: print azure id
              run: echo "${{ secrets.cloud_id }}"
            - name: print id
              run: echo "${{ inputs.id }}"